menu:
  Home: /
  Archives: /archives
  Tags: /tags
  About: /about

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# gitalk
gitalk: true
gitalk_owner: imsuven
gitalk_admin: [imsuven]
gitalk_repo: suven.github.io
gitalk_client_id: e8afff75d67cbfbcd51b
gitalk_client_secret: 51faff4fe6482dc9316256eea973f29a11e3e274

# valine comment
valine: false
leancloud_id:
leancloud_key:

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId: UA-159366081-1

# whether to show read more button when showing article in excerpt in main page
read_more: true
